### ISSUE TITLE
why btrfs? why not NTFS?

### ISSUE THREAD

**Issue by FireGate13** [Trevo525/btrfdeck#6]
I admire your knowledge and courage to modify steamOs scripts. Please can you try and modify them to accept a SDCard with NTFS filesystem ? I know that it can also support symlinks, it can be read and written under fuse/ntfs-3g, and it can support compression.
We can make the mount file to accept both btrfs and ntfs!
Can you try it Trevo525?

**Comment by beltet** [comment]
IMO NTFS is a inferior filesystem to BTRFS. The only reason you would have NTFS is to use it with a windows machine. There are alot of other solutions to come around the need to connect it to other computers. My favorite is syncthing.
But this is my opinion.
Btw, the linux kernel now supports NTFS aswell. you don't need to use nfts-3g anymore.

**Comment by FireGate13** [comment]
I did not say that ntfs is better, but think about how easy it will be to transfer files from win. No extra drivers required and I am sure that steamOs kernel supports ntfs drives. We just have to figure out the right +opts values.

**Comment by beltet** [comment]
I think you justy could edit line 80 in sdcard-mount.sh to:
`    if [[ ${ID_FS_TYPE} != "ext4" && ${ID_FS_TYPE} != "btrfs" && ${ID_FS_TYPE}!=ntfs ]]; then`
And edit line 79 in format-sdcard.sh to:
`mkfs.ntfs -f "$SDCARD_PARTITION"`

But I'm not an expert. and any damages to the deck is your own responsibility.
And if you modify line 76 and 77(or copy it under) you can give the mount process some options. But I don't know what options NTFS has.

**Comment by faandg** [comment]
> think about how easy it will be to transfer files from win

you could create a windows share and connect from deck desktop mode using the cifs/smb protocol.
I'm personally mounting my NAS to transfer files. I'd prefer this method any day over using NTFS

**Comment by Trevo525** [comment]
> > think about how easy it will be to transfer files from win
> 
> you could create a windows share and connect from deck desktop mode using the cifs/smb protocol. I'm personally mounting my NAS to transfer files. I'd prefer this method any day over using NTFS

Well, using a NAS requires you to first have a NAS and then if you have one, you have to copy your date twice. Once to the NAS, then from the NAS to the Steam Deck. I would agree that it's a better option than using NTFS at any capacity. But the best option in my opinion is to use SFTP to copy from Windows to Steam Deck directly. That's how I transfer. 

I enabled SSH in Desktop mode with the following (*I think. Not near my device to double check the commands*) `sudo systemctl start sshd.service`. Then, I edited with the following `nano /etc/sshd.config` and changed the port it's using so that if I ever forget and have it enabled when I am somewhere public, someone port scanning isn't a concern. restart sshd with `sudo systemctl restart sshd.service`, grab your ip of the deck with `ip addr`. Then from Windows, you will download [WinSCP](https://winscp.net/eng/download.php) or FileZilla and connect with sftp, the ip, 'deck' as the username, whatever your password, and the port that you changed previously.

The only caveat of this is that systemctl doesn't seam to start programs in Game Mode. But, that also means that you can know that someone can only ssh/sftp into your device unless you are in desktop mode. I already was using Desktop mode just to configure things anyways, so that works out perfectly for me.

As for this issue/request. I would personally never use NTFS on my Steam Deck. I'm not a 'linux purist' or whatever. But, I think that it holds no value over the default ext4 file system since there are better ways to transfer files to/from the deck. Prove me wrong if you can though. :-) It looks like someone gave the changes above that are needed to adapt this repo into an NTFS version. If someone wants to fork this project, make the changes, and test it I will link to it in my repo here. :-)

**Comment by faandg** [comment]
Perfectly acceptable solution to use scp/sftp, I would however recommend doing some additional security hardening. Security through obscurity (like changing the port) is a start but it does not prevent intruders from getting into your system. You could for example use `AllowUsers deck@<ip>` in `/etc/sshd.config` to only allow user `deck` from a specific device with IP `<ip>`.

Even better, generate a keypair and use key-based authentication instead of password-based authentication ([pick a strong algorithm like ed25519](https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54))

**Comment by Trevo525** [comment]
I do have ssh-keys setup. :-)

This is getting off-topic. Lets continue discussing the issue at hand. I don't have anything more to add and I doubt I will be convinced otherwise. But, my offer still stands. Someone else maintain a repo for ntfs and I will link it in this repo for visibility.

I am closing this, but feel free to open it back up if you have something of value to add :-)
